export { default as About } from './About/About';
export { default as Contact } from './Contact/Contact';
export { default as validate } from './Contact/validate';
export { default as Education } from './Education/Education';
export { default as Home } from './Home/Home';
export { default as NotFound } from './NotFound/NotFound';
export { default as Projects } from './Projects/Projects';
export { default as Skills } from './Skills/Skills';
export { default as Testimonials } from './Testimonials/Testimonials';
